import {assertRecord,evaluate,summarize} from './core.mjs';
export const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=items=>items.length?`<ul>${items.map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ul>`:'<p class="quiet">None recorded.</p>';
export function renderPartialCard(record,{maxCount=null}={}) {
  assertRecord(record);const summary=summarize(record),assessment=evaluate(record,{maxCount});
  return `<article><p class="eyebrow">${escapeHTML(record.subject.system)} · candidate</p><h2>${escapeHTML(summary.count)}</h2><p>${escapeHTML(record.scope.description)}</p><dl>${['knowledge','evidence','work','availability'].map(axis=>`<div><dt>${axis}</dt><dd>${escapeHTML(summary[axis])}</dd></div>`).join('')}</dl><h3>Known items</h3>${list(record.knowledge.known_items.map(x=>x.label))}<h3>What remains unresolved</h3>${list([...record.evidence.missing,...record.evidence.conflicts,...record.work.remaining_units,...record.work.failed_units,...record.availability.missing,...record.availability.unverified])}<p><strong>${escapeHTML(summary.authority)}</strong></p><p>Count limit: ${escapeHTML(assessment.count_limit)}</p><details><summary>Evidence and limits</summary><h3>Recorded support</h3>${list(record.evidence.satisfied)}${list(record.evidence.limitations)}<h3>Holds</h3>${list(assessment.holds)}<p>Captured: ${escapeHTML(record.provenance.captured_at)}</p><p class="digest">${escapeHTML(assessment.record_digest)}</p></details></article>`;
}
export function renderPanel(records,options={}) {
  if(!Array.isArray(records)||!records.length)throw new Error('At least one validated record required');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Quirk partials · private review</title><style>body{margin:0;background:#f3f1e9;color:#242b2b;font:17px/1.5 system-ui,sans-serif}main{max-width:760px;margin:auto;padding:24px 16px 60px}h1{font-size:2rem;line-height:1.1}article{background:white;border:1px solid #c7cfc6;border-radius:16px;padding:20px;margin:22px 0}h2{font-size:1.45rem;line-height:1.3}h3{font-size:1rem;margin-bottom:4px}.eyebrow,.quiet{color:#4e6057}.eyebrow{font-size:.83rem;overflow-wrap:anywhere}dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}dt{text-transform:capitalize;color:#4e6057}dd{margin:0;font-weight:650}ul{padding-left:22px}li,p,.digest{overflow-wrap:anywhere}summary{cursor:pointer;padding:12px 0;min-height:24px}summary:focus-visible{outline:3px solid #146849}.digest{font-size:.7rem}@media(max-width:340px){dl{grid-template-columns:1fr}}</style></head><body><main><p class="eyebrow">QUIRK SYSTEMS / PARTIALS</p><h1>Keep what is known.<br>Show what is unfinished.</h1><p>This saved view reflects the records when it was generated. Review here; changes require a new explicit record. No accounts, connections, or actions are attached.</p>${records.map(r=>renderPartialCard(r,options)).join('')}</main></body></html>`;
}
