-- Quirk Sync Control Plane v0.2 immutable evidence and drift proposals.
-- Append-only evidence.
create or replace function quirk_sync.guard_receipt_insert() returns trigger
language plpgsql set search_path=pg_catalog,quirk_sync as $$
begin
  if new.status in ('succeeded','failed','blocked','cancelled','superseded') and new.receipt_hash is null
    then raise exception 'terminal receipt requires receipt_hash'; end if;
  if new.supersedes_receipt_key is not null and nullif(new.correction_reason,'') is null
    then raise exception 'superseding receipt requires correction_reason'; end if;
  return new;
end $$;
create or replace function quirk_sync.prevent_append_only_mutation() returns trigger
language plpgsql set search_path=pg_catalog,quirk_sync as $$
begin raise exception '% is append-only; write a superseding record instead',tg_table_name; end $$;
drop trigger if exists run_receipts_insert_guard on quirk_sync.run_receipts;
create trigger run_receipts_insert_guard before insert on quirk_sync.run_receipts
for each row execute function quirk_sync.guard_receipt_insert();
drop trigger if exists run_receipts_append_only on quirk_sync.run_receipts;
create trigger run_receipts_append_only before update or delete on quirk_sync.run_receipts
for each row execute function quirk_sync.prevent_append_only_mutation();
drop trigger if exists manifest_transition_ledger_append_only on quirk_sync.manifest_transition_ledger;
create trigger manifest_transition_ledger_append_only before update or delete on quirk_sync.manifest_transition_ledger
for each row execute function quirk_sync.prevent_append_only_mutation();

-- Typed proposals and drift control.
create table if not exists quirk_sync.proposed_moves (
  id bigint generated by default as identity primary key,
  move_key text not null unique,
  object_key text not null,
  move_kind text not null check (move_kind in ('canonical_conflict','projection_drift','identity_collision','human_review','taxonomy_gap','capacity_rebalance','rights_block','provider_boundary')),
  status text not null default 'proposed' check (status in ('proposed','reviewing','approved','rejected','implemented','verified','superseded')),
  reason text not null,
  source_refs jsonb not null default '[]'::jsonb check (jsonb_typeof(source_refs)='array'),
  evidence_refs jsonb not null default '[]'::jsonb check (jsonb_typeof(evidence_refs)='array'),
  requested_right text not null default 'propose',
  authority_ceiling text not null default 'propose',
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload)='object'),
  created_at timestamptz not null default now(),resolved_at timestamptz
);
create or replace function quirk_sync.observe_binding(p_binding_key text,p_observed_hash text,p_source_ref text,p_actor_ref text)
returns jsonb language plpgsql set search_path=pg_catalog,quirk_sync as $$
declare b quirk_sync.source_bindings%rowtype; d boolean; m text;
begin
  if p_observed_hash !~ '^[a-f0-9]{64}$' then raise exception 'invalid observed hash'; end if;
  select * into b from quirk_sync.source_bindings where binding_key=p_binding_key for update;
  if not found then raise exception 'unknown binding_key: %',p_binding_key; end if;
  d:=b.last_synced_hash is not null and b.last_synced_hash<>p_observed_hash;
  update quirk_sync.source_bindings set last_seen_hash=p_observed_hash,last_seen_at=now(),
    state=case when d then 'drifted' else state end,updated_at=now() where id=b.id;
  if d then
    m:='qpm_sync_drift_'||md5(p_binding_key||':'||p_observed_hash);
    insert into quirk_sync.proposed_moves(move_key,object_key,move_kind,reason,source_refs,evidence_refs,payload)
    select m,o.object_key,'projection_drift','Observed hash differs from synchronized hash; silent repair prohibited.',
      jsonb_build_array(p_source_ref),jsonb_build_array('binding://'||p_binding_key),
      jsonb_build_object('actor_ref',p_actor_ref,'binding_key',p_binding_key,'last_synced_hash',b.last_synced_hash,'observed_hash',p_observed_hash)
    from quirk_sync.object_registry o where o.id=b.object_id on conflict(move_key) do nothing;
  end if;
  return jsonb_build_object('binding_key',p_binding_key,'drifted',d,'action',case when d then 'block_and_propose' else 'record_observation' end,'proposed_move_key',m);
end $$;
